# Generated by Django 3.0.5 on 2020-05-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='salaty_max',
            new_name='salary_max',
        ),
    ]
